#!/bin/bash

################################################################
# MAIN
################################################################
# Prompt User for Install Folder
read -p "Enter the installation path or press enter to use the default [~/Applications/MentorHub-DE]: " inputPath
INSTALL_PATH="${inputPath:-"$HOME/Applications/MentorHub-DE"}"

INSTALL_PATH=${INSTALL_PATH/\~/$HOME}

# Append /mentorHub to the install path
INSTALL_PATH="$INSTALL_PATH/mentorHub"

# Create the directory and navigate to it
echo "installing into $INSTALL_PATH"
mkdir -p "$INSTALL_PATH"
cd "$INSTALL_PATH" || exit

# Download the mh script and docker-compose configuration
curl -o "$INSTALL_PATH/mh" https://raw.githubusercontent.com/agile-learning-institute/mentorhub/main/mentorHub-developer-edition/mh 2>> /dev/null

# Initilize Files
touch CURRENT
chmod +x mh
echo "Files Initilized"

# Add to path
echo "Use these commands to add mh to your PATH"
echo '[[ -w ~/.bashrc && -n "$(tail -c1 ~/.bashrc)" ]] && echo >> ~/.bashrc; echo "export PATH=\$PATH:$INSTALL_PATH" >> ~/.bashrc'
echo '[[ -w ~/.zshrc && -n "$(tail -c1 ~/.zshrc)" ]] && echo >> ~/.zshrc; echo "export PATH=\$PATH:$INSTALL_PATH" >> ~/.zshrc'

# Run mh update to pull the latest images and configurations
./mh update

echo "Installation completed. Please restart your terminal or source your shell configuration file to use 'mh'."
echo "$(date) - MentorHub Developers Editioin Installed"

