#!/bin/bash

################################################################
# Update PATH and shell configuration files if they exist
################################################################
update_shell_config() {

	shell="$(basename $SHELL)"
	shell_config="~/.${shell}rc"

	if [[ "$shell" == "bash" || "$shell" == "zsh" ]]; then
		if [ ! -z "$(grep ":$INSTALL_PATH:" <<< ":$PATH:")" ]; then
			echo "$INSTALL_PATH is already in PATH"
		else
			while read -p "$INSTALL_PATH is not in PATH. Modify shell config file? [y/n] " answer; do
				case "$answer" in
					"y")
						if [[ ( $shell == "zsh" && "$PATH" != "$(/usr/bin/env -i zsh +o RCS -o GLOBAL_RCS -c 'echo $PATH')") || ( $shell == "bash" && "$PATH" != "$(/usr/bin/env -i bash --noprofile --rcfile /etc/bash.bashrc --initfile /etc/profile -c 'echo $PATH')" ) ]]; then
							echo "PATH has already been modified by one or more user shell config files. Cannot proceed"
							break
						else
							echo "export PATH=\$PATH:$INSTALL_PATH" >> $shell_config
						fi
						;;
					"n")
						echo "Shell config not modified"
						break
						;;
				esac
			done
		fi
	else
		echo "$shell not supported"
	fi

}

################################################################
# MAIN
################################################################
# Prompt User for Install Folder
read -p "Enter the installation path or press enter to use the default [~/Applications/MentorHub-DE]: " inputPath
INSTALL_PATH="${inputPath:-"$HOME/Applications/MentorHub-DE"}"

INSTALL_PATH=${INSTALL_PATH/\~/$HOME}

# Append /mentorHub to the install path
INSTALL_PATH="$INSTALL_PATH/mentorHub"

# Create the directory and navigate to it
echo "installing into $INSTALL_PATH"
mkdir -p "$INSTALL_PATH"
cd "$INSTALL_PATH" || exit

# Download the mh script and docker-compose configuration
curl -o "$INSTALL_PATH/mh" https://raw.githubusercontent.com/agile-learning-institute/mentorhub/main/mentorHub-developer-edition/mh 2>> /dev/null

# Initilize Files
touch CURRENT
chmod +x mh
echo "Files Initilized"

# Add to path
update_shell_config

# Run mh update to pull the latest images and configurations
./mh update

echo "Installation completed. Please restart your terminal or source your shell configuration file to use 'mh'."
echo "$(date) - MentorHub Developers Editioin Installed"

